Front du calendrier
picasso-utc/chopin pull request #11
Opened 2022-08-16 19:15 UTC by geosaglio

Front du calendrier sans lAPI

2022-08-16 19:51 UTC, maxime-vaillant requested changes

2022-08-16 19:51 UTC, maxime-vaillant commented on src/components/atoms/textDay.jsx
> +                marginLeft: '-8%',
ça non ! C'est quoi l'objectif ? (c'est du hack CSS)

2022-08-16 19:51 UTC, maxime-vaillant commented on src/components/molecules/dayCalendar.jsx
> +    };
Alors là, pas mal celle là, je la note dans mon calepin...
En déconnant moins, la boucle est inutile je te laisse chercher pourquoi.
Et sinon, c'est quoi le const isLight ?

2022-08-16 19:51 UTC, maxime-vaillant commented on src/components/molecules/dayCalendar.jsx
> +            }
Je comprends pas

2022-08-16 19:51 UTC, maxime-vaillant commented on src/components/molecules/dayCalendar.jsx
> +                style={today ? styles.dayToday : islight() ? styles.dayDark : styles.dayLight}
Pareil

2022-08-16 19:51 UTC, maxime-vaillant commented on src/components/molecules/dayCalendar.jsx
> +                        today ? styles.nameToday : islight() ? styles.nameDark : styles.nameLight
Pareil

2022-08-16 19:51 UTC, maxime-vaillant commented on src/components/molecules/dayCalendar.jsx
> +                        today ? styles.nameToday : islight() ? styles.nameDark : styles.nameLight
?

2022-08-16 19:51 UTC, maxime-vaillant commented on src/components/molecules/dayCalendar.jsx
> +                        today ? styles.nameToday : islight() ? styles.nameDark : styles.nameLight
?

2022-08-16 19:58 UTC, geosaglio commented
![Simulator Screen Shot - iPhone 8 - 2022-08-16 at 21 57 29](https://user-images.githubusercontent.com/52065610/184973295-e444f5ef-4593-4508-9312-f73307790451.png)

2022-08-16 21:17 UTC, adrsimon reviewed
rien a ajouter par rapport a ce qu'a dit max

2022-08-17 14:04 UTC, adrsimon approved these changes

2022-08-17 22:58 UTC, maxime-vaillant approved these changes

2022-08-18 08:16 UTC, merged