Newsletter with API info
picasso-utc/chopin pull request #12
Opened 2022-08-17 18:21 UTC by geosaglio

Newsletter avec API just je ne retire que les liens d'image du contenue de la newsletter faudrait retirer les autres markdown markers.

2022-08-17 18:24 UTC, geosaglio commented
https://user-images.githubusercontent.com/52065610/185214466-2253e888-fc11-4107-b31d-c56c6cbe53ca.mp4

2022-08-17 23:03 UTC, maxime-vaillant requested changes

2022-08-17 23:03 UTC, maxime-vaillant commented on src/components/molecules/loadMoreButton.jsx
> +export default LoadMoreButton;
à mettre dans atome 😉

2022-08-17 23:03 UTC, maxime-vaillant commented on src/components/screens/homeScreen.jsx
> +    useEffect(() => {
hésite pas à espacer un peu ton code, pour une meilleure visibilité !

2022-08-17 23:03 UTC, maxime-vaillant commented on src/components/screens/homeScreen.jsx
> +            link2 = link2[0].slice(0, link2[0].length - 1);
Je demande des explications !?

2022-08-21 15:02 UTC, maxime-vaillant requested changes

2022-08-21 15:02 UTC, maxime-vaillant commented on src/api/mocks/mockNewsletter.json
> +    }
On adapte pas l'envoie des données finalement ?

2022-08-21 15:02 UTC, maxime-vaillant commented on src/components/screens/homeScreen.jsx
> +        today.getUTCMilliseconds();
Il y a vraiment pas moyen de faire différemment ? 
Enfin je suis presque sur qu'on peut faire ça plus proprement

2022-08-21 15:02 UTC, maxime-vaillant commented on src/components/screens/homeScreen.jsx
> +    useEffect(() => {
Je up, rajoute un espace entre ton useEffect et tes déclarations de constantes

2022-08-21 15:02 UTC, maxime-vaillant commented on src/components/screens/homeScreen.jsx
> +            link2 = link2[0].slice(0, link2[0].length - 1);
On a plus besoin de regex comme on met l'image à côté ?

2022-08-21 15:02 UTC, maxime-vaillant commented on src/components/screens/homeScreen.jsx
>  export default HomeScreen;
Ça va pas trop en terme de structure ce fichier

2022-08-21 22:28 UTC, maxime-vaillant requested changes

2022-08-21 22:28 UTC, maxime-vaillant commented on src/components/screens/homeScreen.jsx
> +            link2 = link2[0].slice(0, link2[0].length - 1);
Je pense que tu peux enlever ça franchement !

2022-09-09 14:49 UTC, closed without merging