added carte expansion when you click on a category
picasso-utc/chopin pull request #13
Opened 2022-08-17 19:39 UTC by adrsimon

https://user-images.githubusercontent.com/99071153/185227594-f777f4c9-722c-43b1-baaa-f9d5f3f6816e.mov

la vidéo parle d'elle même, j'ai rajouté les affichages des produits de la carte quand tu cliques sur une catégorie

2022-08-17 23:08 UTC, maxime-vaillant requested changes

2022-08-17 23:08 UTC, maxime-vaillant commented on src/components/atoms/productCategoryName.jsx
> +const ProductCategoryName = ({ name, style }) => <Text style={style}>{name}</Text>;
Pas fan de l'écriture en une seule ligne
```suggestion
const ProductCategoryName = ({ name, style }) => (
    <Text style={style}>
        {name}
    </Text>
);
```

2022-08-17 23:08 UTC, maxime-vaillant commented on src/components/molecules/products.jsx
> +const Products = (products) => (
Comment ça se fait que ça fonctionne ?
```suggestion
const Products = ({ products }) => (
```

2022-08-18 08:25 UTC, adrsimon commented on src/components/atoms/productCategoryName.jsx
> +const ProductCategoryName = ({ name, style }) => <Text style={style}>{name}</Text>;
hmmm bah c'est le prettier qui le raccourci comme ça, c'est soit ça soit obligé de faire avec un { return (....) } pour pas que le prettier le raccourcisse

2022-08-18 08:25 UTC, adrsimon commented on src/components/molecules/products.jsx
> +const Products = (products) => (
mdrrr j'avoue zéro idée pq ca fonctionne j'avais pas tilté, mais ca fonctionne

2022-08-18 08:32 UTC, merged