implemented a bottom-tab navigation for the app
picasso-utc/chopin pull request #3
Opened 2022-08-04 17:09 UTC by adrsimon

bottom tab navigation implémentée
changement de .js à .jsx au passage
la police n'est pas la bonne mais je ferai surement une feature/style plus tard, c'est pas la priorité

2022-08-04 17:23 UTC, maxime-vaillant requested changes

2022-08-04 17:23 UTC, maxime-vaillant commented on App.jsx
> +import Navigation from "./src/navigation/navigation";
C'est le perfectionniste en moi qui parle, mais il faudrait fixer des règles d'import (notamment le choix des simple quote ou double quote) et du ; ou non.

2022-08-04 17:23 UTC, maxime-vaillant commented on src/navigation/navigation.jsx
> +import Ionic from 'react-native-vector-icons/Ionicons';
; ou pas comme tu le sens, mais pareil partout par contre

2022-08-04 17:23 UTC, maxime-vaillant commented on src/navigation/navigation.jsx
> +import {createBottomTabNavigator} from "@react-navigation/bottom-tabs";
pareil, et j'ai aussi l'habitude de faire
`import { blabla } from ...`
C'est un choix comme un autre, mais comme le commentaire du haut, juste pareil partout 😉

2022-08-04 17:23 UTC, maxime-vaillant commented on src/navigation/navigation.jsx
> +import {createBottomTabNavigator} from "@react-navigation/bottom-tabs";
pareil, et j'ai aussi l'habitude de faire
`import { blabla } from ...`
C'est un choix comme un autre, mais comme le commentaire du haut, juste pareil partout 😉

2022-08-04 17:23 UTC, maxime-vaillant commented on src/navigation/navigation.jsx
> +                    // eslint-disable-next-line react/prop-types,react/no-unstable-nested-components
Pourquoi il y a un disable ici ? Il faudrait peut être revoir le Linter plutôt !

2022-08-04 17:23 UTC, maxime-vaillant commented on src/screens/calendarScreen.jsx
> +import {View, Text} from "react-native";
Pareil

2022-08-04 17:23 UTC, maxime-vaillant commented on src/screens/carteScreen.jsx
> +import {View, Text} from "react-native";
Pareil

2022-08-04 17:24 UTC, maxime-vaillant commented
Il faudrait prévoir une nomenclature (c'est d'ailleurs normalement le rôle du prettier, il marche ?)
Sinon nickel !

2022-08-05 07:42 UTC, adrsimon commented
le prettier était censé fonctionner je crois que c'est bon pourtant, j'ai changé ce que t'as dit du coup et j'ai rajouté les rules qu'augustin avait fait dans l'ancien linter comme ça c'est bon

2022-08-05 14:34 UTC, maxime-vaillant approved these changes

2022-08-05 15:44 UTC, merged