Feature/newsletter
picasso-utc/chopin pull request #5
Opened 2022-08-09 14:24 UTC by geosaglio

Front de la newsletter sans les infos de l'api et le sondage qui n'est pas encore fonctionel

2022-08-09 17:14 UTC, maxime-vaillant requested changes
Alors, il y a beaucoup de chose à dire, mais c'est normal 😉

- Oublie pas de rebase assez souvent pour éviter les conflits (comme ici)

- En ce qui concerne la structure, je ne comprends pas d'où vient le 'components', 'atoms' devrait être dans components et news/latestNews devrait être dans 'molecules'.

- Sur le principe de React, j'ai essayé de t'expliquer ça un peu plus haut, si c'est pas clair on peut passer en priver, mais là par exemple, il y a pas besoin d'avoir 'news' et 'latestNews', juste News suffit, bien paramètre, et au niveau de l'élément parent, un bon paramétrage.

Sinon, c'est un bon début 😉

2022-08-09 17:14 UTC, maxime-vaillant commented on package.json
> +    "@rneui/themed": "^4.0.0-rc.6",
C'est quoi ces deux packages ? À quoi ils servent ?

2022-08-09 17:14 UTC, maxime-vaillant commented on src/atoms/headerLatestNews.jsx
> +            >PERM HALLOWEEN</Text>
Alors, ici ce qui va pas, c'est dans le principe d'un composant.
Dans l'idée, on va créer un composant très générique, c'est à dire presque comme tu l'as fais, mais on le paramètre.
Là dans cet exemple, on aurait quelque chose comme :
```
function HeaderLatestNews({ content }) {
...
{content}
...
}
```

Comme ça, quand on appelle le composant en question, on lui envoie le contenu en question et pas besoin de refaire 3 fois la même chose

2022-08-09 17:14 UTC, maxime-vaillant commented on src/atoms/headerLatestNews.jsx
> +            >PERM HALLOWEEN</Text>
D'ailleurs, à voir avec @adrsimon, mais personnellement, je préfère :
`const HeaderLatestNews = ({ content }) => {}`
à
`function HeaderLatestNews({ content }) {}`

2022-08-09 17:14 UTC, maxime-vaillant commented on src/atoms/imageNews.jsx
> +import {Image} from 'react-native';
```suggestion
import { Image } from 'react-native';
```

2022-08-09 17:14 UTC, maxime-vaillant commented on src/atoms/textNews.jsx
> +import {Text} from 'react-native';
```suggestion
import { Text } from 'react-native';
```

2022-08-09 17:14 UTC, maxime-vaillant commented on src/atoms/textNews.jsx
> +function TextNews(){
```suggestion
function TextNews({ content }){
```

2022-08-09 17:14 UTC, maxime-vaillant commented on src/atoms/textNews.jsx
> +            Le Pic sera fermé à Etuville frère on veut aller au Parc Astérix aussi hein ça va être bad lourd pour une fois on profitera sans servir des bières là...
```suggestion
            {content}
```

2022-08-09 17:14 UTC, maxime-vaillant commented on src/screens/homeScreen.jsx
>  function HomeScreen() {
espace bien ta fonction de tes imports

2022-08-09 17:15 UTC, maxime-vaillant commented
@adrsimon je te laisse compléter si j'ai oublier des choses

2022-08-09 20:46 UTC, adrsimon commented on src/atoms/headerLatestNews.jsx
> +            >PERM HALLOWEEN</Text>
yep assez d'acc avec ça go sur cette syntaxe!

2022-08-09 20:50 UTC, adrsimon commented on package.json
> +    "@rneui/themed": "^4.0.0-rc.6",
je sais pas non plus, en plus ils m'ont pas l'air utilisés

2022-08-09 20:59 UTC, adrsimon commented
j'ai pas beaucoup plus de choses à dire par rapport à ce que max à dit je suis globalement d'accord sur toutes les remarques, hésite pas sur le groupe si t'as des questions!!

2022-08-14 08:06 UTC, adrsimon requested changes
attend la review de max mais moi ca m'a l'air carré du coup!!

la structure est compréhensible et ca a l'air de bien fonctionner (j'ai pas testé mais c'est cohérent donc bon), et c'est plus propre qu'avant, donc cool bravo

juste par rapport aux fichiers de l'api qui se sont retrouvés dans ton push je sais pas trop à quoi c'est du mais normalement ca devrait pas y être vu que cette branche a deja été merge sur develop, et j'ai pas l'impresison que les fichiers aient spécifiquement bougé dans l'archi du projet, donc y'a pas de raison que ca y soit

2022-08-14 08:06 UTC, adrsimon commented on package.json
> +    "axios-mock-adapter": "^1.21.1",
tu devrais pas avoir ça normalement dans le commit, la y'a tout les trucs du feature/mock-api qui ont été rajoutés, il doit manquer un rebase ou qqch

2022-08-14 08:06 UTC, adrsimon commented on src/api/apiCalls.js
> +}
du coup idem ca devrait pas etre dans le push

2022-08-14 08:06 UTC, adrsimon commented on src/api/config.js
> +}
idem

2022-08-14 08:06 UTC, adrsimon commented on src/api/mocks/mockNewsletter.json
> +]
idem

2022-08-14 08:06 UTC, adrsimon commented on src/components/molecules/news.jsx
> +              style = {{
c'est pour tatilloner mais le style devrait pas être identé la normalement

2022-08-14 08:06 UTC, adrsimon commented on yarn.lock
> +
du coup les packages ont été mis dans le push aussi

2022-08-14 08:14 UTC, adrsimon commented on src/api/apiCalls.js
> +}
(ptite précision : je parle du fichier entier)

2022-08-14 16:57 UTC, maxime-vaillant requested changes
Il faudrait reprendre cette histoire de rebase, pour avoir tout propre, mais sinon c'est carrément mieux !
Est-ce que c'est possible d'avoir un petit screen de ce que ça donne aussi ?

2022-08-14 16:57 UTC, maxime-vaillant commented on package.json
> +    "axios-mock-adapter": "^1.21.1",
exactement

2022-08-14 16:57 UTC, maxime-vaillant commented on src/components/atoms/imageNews.jsx
> +import {Image} from 'react-native';
Le prettier fonctionne pas ?

2022-08-14 16:57 UTC, maxime-vaillant commented on src/components/atoms/imageNews.jsx
> +const ImageNews = ({lien}) => {
`{ lien }`

2022-08-14 16:57 UTC, maxime-vaillant commented on src/components/atoms/imageNews.jsx
> +    <Image
Problème d'indentation ici

2022-08-14 16:57 UTC, maxime-vaillant commented on src/components/atoms/textNews.jsx
> +import {Text} from 'react-native';
Prettier

2022-08-14 16:57 UTC, maxime-vaillant commented on src/components/molecules/news.jsx
> +              style = {{
exact

2022-08-14 20:36 UTC, adrsimon commented on src/components/atoms/imageNews.jsx
> +import {Image} from 'react-native';
il fonctionne chez moi, je pense que ca doit venir de son IDE qui est pas config

2022-08-15 14:06 UTC, merged